/** Plain-language definitions shown by the <Term> tooltip. */
export const GLOSSARY: Record<string, string> = {
  ROE: 'Rules of engagement. Hold fire: hostiles get the first shot. Return fire: engage only identified hostiles. Weapons free: first strike, but unidentified civilians may be hit (incidents cost political capital).',
  LITTORAL: 'Shallow coastal water (0 to -0.15 depth). Hazardous to deep-draft hulls; ideal for small missile boats.',
  FRICTION: 'Integration friction: modules whose protocol differs from the CMS slow its reaction time and add sensor tracking lag, until R&D completes a protocol bridge.',
  HULK: 'Parts hulk: a docked ship stripped for modules so frontline ships can be repaired when spares run out.',
  TEMPO: 'Rotate thirds: automatic Patrol / Workup / Overhaul cycling. Surge: rotation suspended for maximum presence, at the price of breakdowns.',
  THIRDS: 'Rule of Thirds: about a third of the fleet on patrol, a third working up or in transit, a third in overhaul.',
  STANDING: 'Diplomatic standing with a vendor state (0-100). Tier = standing / 25 gates catalogue lines; 65+ averts a pending sanction.',
  THREAT: 'How hard the enemy probes a sector. Rises with tension and when a sector is left uncovered; more hostile contacts appear.',
  SUPPORT: 'Domestic support: how willing the civilian government is to back the navy. It sets next year\'s appropriation and political capital income. Below 40 lobbying costs more; below 25 ministries refuse contact and political capital drains; below 10 a parliamentary inquiry freezes procurement and cuts the budget.',
  FISCAL: 'The navy is funded by an annual appropriation paid in four quarterly tranches. Unspent money above 15% of the appropriation returns to the Treasury at year end, and spending too slowly shrinks next year\'s forecast.',
  SOP: 'Standing operating procedure: what task forces do on their own when an unknown contact comes near. Observe = shadow and identify visually. Challenge = hail, warn the silent, board runners. Assertive = hail early and board silent contacts without warning. ROE is the ceiling on firing.',
  LADDER: 'Shadow, hail, warn, board, engage. Each step reveals something about a contact and carries a risk; ROE caps engagement. Orders here override the sector SOP for this contact only.',
  RELATIONS: 'Relationship ladder: Contact → Trade mission → Framework agreement (tier-0 lines) → Signed (tiers by standing) → Strategic partner. Each step costs political capital and days; later steps also cost money and need standing. Courting the Eastern bloc costs standing with western vendors.',
  DILIGENCE: 'Due diligence: auditors trace every foreign component inside a vendor\'s products. A product can hide another state\'s parts; if that state sanctions you, the product is frozen or embargoed too. Unverified modules may or may not hide anything.',
  CONTRACT: 'Build contract: 30% deposit at lay-down, the balance paid daily while the hull builds (a frozen hull pays nothing; without money the slipway waits). Cancelling refunds each vendor by who broke the deal: a vendor whose state sanctions the kit owes a refund at its regime\'s rate; walking away from a vendor that could deliver refunds 40% and costs standing; the yards salvage half the hull work. From 40% built a hull can be sold to a third-party navy for 70% of what was paid.',
  SHIPPING: 'Civilian ships sail identified along shipping lanes. Attacks and high sector threat raise a lane\'s war-risk premium; higher premiums thin its traffic, and past a limit shipping reroutes away for a month. The trade index (100 = normal) lowers next year\'s appropriation and drains domestic support when it falls.',
  ESCORT: 'A task force within 14 tiles, or one on station in the ship\'s sector, protects a merchant ship; raiders hunt unprotected lane traffic. Order an escort to shadow a ship all the way to port (support +0.5 on arrival) or to answer a distress call. The task force leaves its sector uncovered while it escorts.',
  TENSION: 'Global geopolitical tension. Raises the chance that vendor states revoke licences, freeze exports or embargo spares.',
};
